PRINT N'CREATE DB HospitalChat1'
GO

CREATE DATABASE [HospitalChat1]
GO

USE [HospitalChat1]
GO

PRINT N'CREATE TABLE Users'
GO

CREATE TABLE [dbo].[Users](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[userLogin] [varchar](15) NOT NULL,
	[userName] [varchar](80) NOT NULL,
	[userPassword] [varchar](50) NOT NULL,
	[userReferenceID] [int] NULL,
	[userCreationUser] [datetime] NULL,
	[userReferenceRef] [int] NULL,
 CONSTRAINT [PK_USER_USERID] PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

PRINT N'CREATE TABLE GROUPS'
GO

PRINT N'CREATE TABLE Roles'
GO

CREATE TABLE [dbo].[Roles](
	[roleID] [int] IDENTITY(1,1) NOT NULL,
	[roleName] [varchar](80) NOT NULL,
 CONSTRAINT [PK_ROLES_ROLEID] PRIMARY KEY CLUSTERED 
(
	[roleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

PRINT N'CREATE TABLE UserRole'
GO

CREATE TABLE [dbo].[UserRole](
	[userID] [int] NOT NULL,
	[roleID] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_USERROLE_USER_USERID] FOREIGN KEY([userID])
REFERENCES [dbo].[Users] ([userID])
GO

ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_USERROLE_USER_USERID]
GO


CREATE TABLE [dbo].[Groups](
	[groupID] [int] IDENTITY(1,1) NOT NULL,
	[groupName] [varchar](80) NOT NULL,
	[groupReference] [int] NULL,
 CONSTRAINT [PK_GROUPS_GROUPID] PRIMARY KEY CLUSTERED 
(
	[groupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

PRINT N'CREATE TABLE GROUPUSER'
GO

CREATE TABLE [dbo].[GroupUser](
	[groupID] [int] NOT NULL,
	[userID] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GroupUser]  WITH CHECK ADD  CONSTRAINT [FK_GROUPUSER_GROUP_GROUPID] FOREIGN KEY([groupID])
REFERENCES [dbo].[Groups] ([groupID])
GO

ALTER TABLE [dbo].[GroupUser] CHECK CONSTRAINT [FK_GROUPUSER_GROUP_GROUPID]
GO

ALTER TABLE [dbo].[GroupUser]  WITH CHECK ADD  CONSTRAINT [FK_GROUPUSER_USER_USERID] FOREIGN KEY([userID])
REFERENCES [dbo].[Users] ([userID])
GO

ALTER TABLE [dbo].[GroupUser] CHECK CONSTRAINT [FK_GROUPUSER_USER_USERID]
GO

PRINT N'CREATE TABLE Messages'
GO

CREATE TABLE [dbo].[Messages](
	[MessageID] [int] IDENTITY(1,1) NOT NULL,
	[to] [int] NOT NULL,
	[from] [int] NOT NULL,
	[date] [datetime] NOT NULL,
	[text] [varchar](max) NULL,
 CONSTRAINT [PK_MESSAGE_MESSAGEID] PRIMARY KEY CLUSTERED 
(
	[MessageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

PRINT N'CREATE TABLE Reference'
GO

CREATE TABLE [dbo].[Reference](
	[ReferenceID] [int] IDENTITY(1,1) NOT NULL,
	[ReferenceLink] [varchar](max) NULL,
 CONSTRAINT [PK_REFERENCE_REFERENCEID] PRIMARY KEY CLUSTERED 
(
	[ReferenceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

PRINT N'CREATE TABLE MsgReference'
GO

CREATE TABLE [dbo].[MsgReference](
	[ReferenceID] [int] IDENTITY(1,1) NOT NULL,
	[MessageID] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MsgReference]  WITH CHECK ADD  CONSTRAINT [FK_MSGREFERENCE_MESSAGE_MESSAGEID] FOREIGN KEY([MessageID])
REFERENCES [dbo].[Messages] ([MessageID])
GO

ALTER TABLE [dbo].[MsgReference] CHECK CONSTRAINT [FK_MSGREFERENCE_MESSAGE_MESSAGEID]
GO

ALTER TABLE [dbo].[MsgReference]  WITH CHECK ADD  CONSTRAINT [FK_MSGREFERENCE_REFERENCE_REFERENCEID] FOREIGN KEY([ReferenceID])
REFERENCES [dbo].[Reference] ([ReferenceID])
GO

ALTER TABLE [dbo].[MsgReference] CHECK CONSTRAINT [FK_MSGREFERENCE_REFERENCE_REFERENCEID]
GO



